#!/bin/sh

# ------------------------------- TAWAN -----------------------------------

#question name (LabXY) = 1st parameter
lab_name=$1

#slice LabXY to LabX (first layer directory name)
len=${#lab_name}
len=$(echo `expr $len - 1`)
lab_num=`echo $lab_name | cut -c 1-$len`

#answer = 2nd parameter
answer=$2

#remove former result file
if [ -e "result$lab_name.txt" ]
then
	rm "result$lab_name.txt"             
fi

# --------------------------------- GUY -----------------------------------

#goto Labs folder
cd Labs

#if folder LabX exist
if [ -e $lab_num ]
then
	#goto that folder
	cd $lab_num
else
	#print error message
	echo "$lab_num does not exist"
	#terminates program
	exit 1
fi


# ------------------------------- MOST ----------------------------------

#set positional parameters($1, $2, ..., $n) to name of files and folders in current directory
#in this case, folder of students.
set `ls`

#print separator line
echo "----------------------------------------"
#for item in those file/folder names
for item in $*	
# -------------------------------- PUNN -----------------------------------
do
	#if the name is directory
	if [ -d $student_id ]
    	then
		#print student id
		echo $student_id

		#go in
        	cd $student_id
		if [ -e $lab_name.c ]
		then
			if gcc $lab_name.c -o temp;
			then
		      		#compile success
		      		echo "compile ok"

		      		#generate temp files

		      		./temp > student_result.txt
		      		echo $answer > teacher_result.txt

					# --------------------------- DAMIAN ----------------------------------

		      		#evaluate result
					student="$(cat student_result.txt)"
					teacher="$(cat teacher_result.txt)"
		      		if [ "$student" = "$teacher" ];
		      		then
		            		#answer correct
		            		echo "correct answer"
		            		score=3
		      		else
		            		#answer wrong
		            		echo "wrong answer"
		            		score=2
		      		fi

				#clear temp files
				rm student_result.txt
				rm teacher_result.txt
				rm temp

			else
		     		#compile error
		     		echo "compile failed"
		     		score=1
		 	fi		
		else
			#C file does not exist
			echo "missing $lab_name.c"
        		score=0
		fi
		cd ../../..
		#file result to file
	       	echo "$student_id;$score" >> "result$lab_name.txt"
		cd Labs/$lab_num
		
		#print separator line
		echo "----------------------------------------"
       	fi
done


# -------------------------------------------------------------------------------