#!/bin/sh

lab_name=${1:0:4}
cd Labs

if [ -e $lab_name ]
then
	cd $lab_name
else
	echo "$lab_name does not exist"
	exit 1
fi

set `ls`
for item in $*
do
	if [ -d $item ]
	then
		cd $item
		#do some shit
		cd ..
	fi
done
	
